//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int idInspeccion { get; set; }
        public int IdVehiculo { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public string Ralladura { get; set; }
        public string Cantidad_combustible { get; set; }
        public string Goma_respuesta { get; set; }
        public string Gato { get; set; }
        public string Rotura_cristal { get; set; }
        public string goma_sup_izq { get; set; }
        public string goma_sup_der { get; set; }
        public string goma_inf_izq { get; set; }
        public string goma_inf_der { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
