//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Renta_Devolucion = new HashSet<Renta_Devolucion>();
            this.Renta_Devolucion_Copia = new HashSet<Renta_Devolucion_Copia>();
            this.Inspeccion = new HashSet<Inspeccion>();
        }
    
        public int idVehiculo { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public int IdTipoVehiculo { get; set; }
        public int IdTipoCombustible { get; set; }
        public int No_chahis { get; set; }
        public int No_motor { get; set; }
        public int No_placa { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Devolucion> Renta_Devolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Devolucion_Copia> Renta_Devolucion_Copia { get; set; }
        public virtual Tipo_combustible Tipo_combustible { get; set; }
        public virtual Tipo_vehiculo Tipo_vehiculo { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    }
}
